# Generated by Django 4.0.1 on 2022-01-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='interpreting',
            new_name='interpreting_requested',
        ),
    ]
