# Generated by Django 4.0.1 on 2022-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0002_rename_interpreting_team_interpreting_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Active'), ('D', 'Defeated')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='bracket_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Coed')], default='M', max_length=1),
        ),
    ]
