# Generated by Django 4.0.1 on 2022-01-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0003_team_team_status_alter_team_bracket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bracket_type',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Coed', 'Coed')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Active', 'Active'), ('Inactive', 'Defeated')], default='Registered', max_length=20),
        ),
    ]
