# Generated by Django 4.0.1 on 2022-01-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0005_pit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='MudTug.team'),
        ),
        migrations.AlterField(
            model_name='pit',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='MudTug.team'),
        ),
    ]
