# Generated by Django 4.0.1 on 2022-01-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0006_alter_pit_team1_alter_pit_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit',
            name='bracket_type',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Coed', 'Coed')], default='Male', max_length=20),
        ),
    ]
