# Generated by Django 4.0.1 on 2022-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MudTug', '0007_pit_bracket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='victories',
            field=models.IntegerField(default=0),
        ),
    ]
